RABBIT_MQ_HOST = 'RABBIT_MQ_HOST'
RABBIT_MQ_START_TRAINING_CHANNEL = 'rabbit_mq_start_training'

SQLALCHEMY_DATABASE_URI = 'SQLALCHEMY_DATABASE_URI'

FLASK_APP = 'FLASK_APP'

SECRET_KEY = 'SECRET_KEY'

POSTGRES_USER = 'POSTGRES_USER'
POSTGRES_PASSWORD = 'POSTGRES_PASSWORD'
POSTGRES_DB = 'POSTGRES_DB'

POSTGRES_HOST = 'POSTGRES_HOST'
POSTGRES_PORT = 'POSTGRES_PORT'

FLASK_CONDA_ENV_NAME = 'FLASK_CONDA_ENV_NAME'

DATASETS_FOLDER = "DATASETS_FOLDER"
RESULTS_FOLDER = "RESULTS_FOLDER"
DOWNLOADS_FOLDER = "DOWNLOADS_FOLDER"

MODEL_LITTLE = 'little'
MODEL_MEDIUM = 'medium'
MODEL_LARGE = 'large'
