RABBIT_MQ_HOST = 'rabbit_mq_host'
RABBIT_MQ_START_TRAINING_CHANNEL = 'rabbit_mq_start_training'

SQLALCHEMY_DATABASE_URI = 'SQLALCHEMY_DATABASE_URI'

FLASK_APP = 'FLASK_APP'

SECRET_KEY = 'SECRET_KEY'

POSTGRES_USER = 'POSTGRES_USER'
POSTGRES_PASSWORD = 'POSTGRES_PASSWORD'
POSTGRES_DB = 'POSTGRES_DB'

POSTGRES_HOST = 'POSTGRES_HOST'
POSTGRES_PORT = 'POSTGRES_PORT'

FLASK_CONDA_ENV_NAME = 'FLASK_CONDA_ENV_NAME'
